version: '3'

services:
  kong-db
    image: postgres:14.5
    container_name: kong-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
      - POSTGRES_PASSWORD=kong
    volumes:
      - "kong-db-data:/var/lib/postgresql/data"

  kong-migrations:
    image: kong
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-db
      - KONG_PG_PASSWORD=kong
      - KONG_CASSANDRA_CONTACT_POINTS=kong-db
    command: kong migrations bootstrap
    restart: on-failure
    depends_on:
      - kong-db

  kong:
    image: kong
    container_name: kong.briscola-api.net 
#    volumes:
#      - ./ssl:/etc/kong/ssl
    environment:
#      - KONG_SSL_CERT=/etc/kong/ssl/fullchain.pem
#      - KONG_SSL_CERT_KEY=/etc/kong/ssl/privkey.pem
      - LC_CTYPE=ja_JP.UTF-8
      - LC_ALL=ja_JP.UTF-8
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-db
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
      - KONG_CASSANDRA_CONTACT_POINTS=kong-db
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
    restart: on-failure
    ports:
      - 443:8443
      - 8001:8001
    links:
      - kong-db:kong-db
    depends_on:
      - kong-migrations

volumes:
  kong-db-data:
